package messages.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motion_detect.proto

public final class MotionDetect {
    private MotionDetect() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface MotionDetectMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:MotionDetectMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 expectedDistanceCm = 1;</code>
         */
        boolean hasExpectedDistanceCm();
        /**
         * <code>optional int32 expectedDistanceCm = 1;</code>
         */
        int getExpectedDistanceCm();

        /**
         * <code>optional int32 triggeredDistanceCm = 2;</code>
         */
        boolean hasTriggeredDistanceCm();
        /**
         * <code>optional int32 triggeredDistanceCm = 2;</code>
         */
        int getTriggeredDistanceCm();
    }
    /**
     * Protobuf type {@code MotionDetectMessage}
     */
    public  static final class MotionDetectMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:MotionDetectMessage)
            MotionDetectMessageOrBuilder {
        // Use MotionDetectMessage.newBuilder() to construct.
        private MotionDetectMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private MotionDetectMessage() {
            expectedDistanceCm_ = 0;
            triggeredDistanceCm_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private MotionDetectMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            expectedDistanceCm_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            triggeredDistanceCm_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MotionDetect.internal_static_MotionDetectMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MotionDetect.internal_static_MotionDetectMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MotionDetect.MotionDetectMessage.class, MotionDetect.MotionDetectMessage.Builder.class);
        }

        private int bitField0_;
        public static final int EXPECTEDDISTANCECM_FIELD_NUMBER = 1;
        private int expectedDistanceCm_;
        /**
         * <code>optional int32 expectedDistanceCm = 1;</code>
         */
        public boolean hasExpectedDistanceCm() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 expectedDistanceCm = 1;</code>
         */
        public int getExpectedDistanceCm() {
            return expectedDistanceCm_;
        }

        public static final int TRIGGEREDDISTANCECM_FIELD_NUMBER = 2;
        private int triggeredDistanceCm_;
        /**
         * <code>optional int32 triggeredDistanceCm = 2;</code>
         */
        public boolean hasTriggeredDistanceCm() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 triggeredDistanceCm = 2;</code>
         */
        public int getTriggeredDistanceCm() {
            return triggeredDistanceCm_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, expectedDistanceCm_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, triggeredDistanceCm_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, expectedDistanceCm_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, triggeredDistanceCm_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MotionDetect.MotionDetectMessage)) {
                return super.equals(obj);
            }
            MotionDetect.MotionDetectMessage other = (MotionDetect.MotionDetectMessage) obj;

            boolean result = true;
            result = result && (hasExpectedDistanceCm() == other.hasExpectedDistanceCm());
            if (hasExpectedDistanceCm()) {
                result = result && (getExpectedDistanceCm()
                        == other.getExpectedDistanceCm());
            }
            result = result && (hasTriggeredDistanceCm() == other.hasTriggeredDistanceCm());
            if (hasTriggeredDistanceCm()) {
                result = result && (getTriggeredDistanceCm()
                        == other.getTriggeredDistanceCm());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasExpectedDistanceCm()) {
                hash = (37 * hash) + EXPECTEDDISTANCECM_FIELD_NUMBER;
                hash = (53 * hash) + getExpectedDistanceCm();
            }
            if (hasTriggeredDistanceCm()) {
                hash = (37 * hash) + TRIGGEREDDISTANCECM_FIELD_NUMBER;
                hash = (53 * hash) + getTriggeredDistanceCm();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MotionDetect.MotionDetectMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static MotionDetect.MotionDetectMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static MotionDetect.MotionDetectMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static MotionDetect.MotionDetectMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(MotionDetect.MotionDetectMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code MotionDetectMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:MotionDetectMessage)
                MotionDetect.MotionDetectMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MotionDetect.internal_static_MotionDetectMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MotionDetect.internal_static_MotionDetectMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MotionDetect.MotionDetectMessage.class, MotionDetect.MotionDetectMessage.Builder.class);
            }

            // Construct using MotionDetect.MotionDetectMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                expectedDistanceCm_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                triggeredDistanceCm_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MotionDetect.internal_static_MotionDetectMessage_descriptor;
            }

            public MotionDetect.MotionDetectMessage getDefaultInstanceForType() {
                return MotionDetect.MotionDetectMessage.getDefaultInstance();
            }

            public MotionDetect.MotionDetectMessage build() {
                MotionDetect.MotionDetectMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public MotionDetect.MotionDetectMessage buildPartial() {
                MotionDetect.MotionDetectMessage result = new MotionDetect.MotionDetectMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.expectedDistanceCm_ = expectedDistanceCm_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.triggeredDistanceCm_ = triggeredDistanceCm_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MotionDetect.MotionDetectMessage) {
                    return mergeFrom((MotionDetect.MotionDetectMessage)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MotionDetect.MotionDetectMessage other) {
                if (other == MotionDetect.MotionDetectMessage.getDefaultInstance()) return this;
                if (other.hasExpectedDistanceCm()) {
                    setExpectedDistanceCm(other.getExpectedDistanceCm());
                }
                if (other.hasTriggeredDistanceCm()) {
                    setTriggeredDistanceCm(other.getTriggeredDistanceCm());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                MotionDetect.MotionDetectMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MotionDetect.MotionDetectMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int expectedDistanceCm_ ;
            /**
             * <code>optional int32 expectedDistanceCm = 1;</code>
             */
            public boolean hasExpectedDistanceCm() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional int32 expectedDistanceCm = 1;</code>
             */
            public int getExpectedDistanceCm() {
                return expectedDistanceCm_;
            }
            /**
             * <code>optional int32 expectedDistanceCm = 1;</code>
             */
            public Builder setExpectedDistanceCm(int value) {
                bitField0_ |= 0x00000001;
                expectedDistanceCm_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 expectedDistanceCm = 1;</code>
             */
            public Builder clearExpectedDistanceCm() {
                bitField0_ = (bitField0_ & ~0x00000001);
                expectedDistanceCm_ = 0;
                onChanged();
                return this;
            }

            private int triggeredDistanceCm_ ;
            /**
             * <code>optional int32 triggeredDistanceCm = 2;</code>
             */
            public boolean hasTriggeredDistanceCm() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>optional int32 triggeredDistanceCm = 2;</code>
             */
            public int getTriggeredDistanceCm() {
                return triggeredDistanceCm_;
            }
            /**
             * <code>optional int32 triggeredDistanceCm = 2;</code>
             */
            public Builder setTriggeredDistanceCm(int value) {
                bitField0_ |= 0x00000002;
                triggeredDistanceCm_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 triggeredDistanceCm = 2;</code>
             */
            public Builder clearTriggeredDistanceCm() {
                bitField0_ = (bitField0_ & ~0x00000002);
                triggeredDistanceCm_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:MotionDetectMessage)
        }

        // @@protoc_insertion_point(class_scope:MotionDetectMessage)
        private static final MotionDetect.MotionDetectMessage DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new MotionDetect.MotionDetectMessage();
        }

        public static MotionDetect.MotionDetectMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<MotionDetectMessage>
                PARSER = new com.google.protobuf.AbstractParser<MotionDetectMessage>() {
            public MotionDetectMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MotionDetectMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MotionDetectMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MotionDetectMessage> getParserForType() {
            return PARSER;
        }

        public MotionDetect.MotionDetectMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MotionDetectMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_MotionDetectMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\023motion_detect.proto\"N\n\023MotionDetectMes" +
                        "sage\022\032\n\022expectedDistanceCm\030\001 \001(\005\022\033\n\023trig" +
                        "geredDistanceCm\030\002 \001(\005"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_MotionDetectMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_MotionDetectMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_MotionDetectMessage_descriptor,
                new java.lang.String[] { "ExpectedDistanceCm", "TriggeredDistanceCm", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
